<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Book + Pay Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'pay.html',
	'resources' => array(
		'checkbox_checked' => 'Selected',
		'checkbox_unchecked' => 'Unselected',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'hebreunion2019@gmail.com',
		'to' => 'hebreunion2019@gmail.com'
	),
	'recaptcha2' => array(
		'private_key' => 'null'
	),
	'fields' => array(
		'custom_U7263' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Full Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Full Name\' is required.'
			)
		),
		'custom_U7298' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Schools Attended',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Schools Attended\' is required.'
			)
		),
		'custom_U7273' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Name to Display on Badge',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name to Display on Badge\' is required.'
			)
		),
		'custom_U7339' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Postal Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Postal Address\' is required.'
			)
		),
		'custom_U7281' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Postcode',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Postcode\' is required.'
			)
		),
		'custom_U7277' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Date of Birth',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Date of Birth\' is required.'
			)
		),
		'custom_U7285' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'e-Mail Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'e-Mail Address\' is required.'
			)
		),
		'custom_U7268' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Preferred School for Seating Plan',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Preferred School for Seating Plan\' is required.'
			)
		),
		'custom_U7327' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Dietary or Accessibility Requirements',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7335' => array(
			'order' => 13,
			'type' => 'checkbox',
			'label' => 'I have read and agree to the Terms and Conditions as listed on the left of this form',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'I have read and agree to the Terms and Conditions as listed on the left of this form\' is required.'
			)
		),
		'g-recaptcha-response' => array(
			'order' => 14,
			'type' => 'recaptcha2',
			'label' => 'Verification',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Verification\' is required.',
				'format' => 'Incorrect reCAPTCHA 2.0 value.'
			)
		),
		'custom_U8187' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Maiden Name',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7302' => array(
			'order' => 11,
			'type' => 'radiogroup',
			'label' => 'Partner Attending Saturday Night',
			'required' => true,
			'optionItems' => array(
				'Yes  (Additional £35)',
				'No'
			),
			'errors' => array(
				'required' => 'Field \'Partner Attending Saturday Night\' is required.',
				'format' => 'Field \'Partner Attending Saturday Night\' has an invalid value.'
			)
		),
		'custom_U7312' => array(
			'order' => 10,
			'type' => 'checkboxgroup',
			'label' => 'I will be attending',
			'required' => true,
			'optionItems' => array(
				'Friday and Saturday Nights (£85)',
				'Friday Night Only (£55)',
				'Saturday Night Only (£35)',
				'Family Fun Day (Saturday Afternoon - Free)'
			),
			'errors' => array(
				'required' => 'Field \'I will be attending\' is required.',
				'format' => 'Field \'I will be attending\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
